version: "3.8"

services:
  hotel_db:
    image: mysql:latest
    container_name: hotel_db
    restart: always
    networks:
      - hdv_network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_RANDOM_ROOT_PASSWORD: false
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: db_hotel
    # ports:
    #   - "3306:3306"
    volumes:
      - hotel-mysql-data:/var/lib/mysql

  hotel_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_service
    depends_on:
      - hotel_db
    ports:
      - "3004:3004"
    networks:
      - hdv_network
    environment:
      IP: hotel_service
      PORT: 3004
      DB_IP: hotel_db
      DB_PORT: 3306
      DB_DIALECT: mysql
      DB_NAME: db_hotel
      DB_USER: sa
      DB_PASS: 1
      DB_GEN: 0

networks:
  hdv_network:
    driver: bridge
volumes:
  hotel-mysql-data:
